@startuml
actor Docente as D
actor Cuidador as C
actor Niño as N
actor "Minedu" as M

package "Frontend" {
    [Aplicación Android (Kotlin)] <<MobileApp>>
    [Aplicación iOS (SwiftUI)] <<MobileApp>>
    [Progressive Web App (PWA)] <<WebApp>>
}

package "Backend" {
    component "API Gateway" as APIGW
}


package "Servicios de RA" {
    component "ARCore (Android)" as ARCore
    component "ARKit (iOS)" as ARKit
}


D --> [Progressive Web App (PWA)] : Planificar actividades
C --> [Aplicación Android (Kotlin)] : Supervisar actividades
N --> [Aplicación Android (Kotlin)] : Participar en RA
C --> [Aplicación iOS (SwiftUI)] : Supervisar actividades
N --> [Aplicación iOS (SwiftUI)] : Participar en RA
M --> [Progressive Web App (PWA)] : Consultar reportes

[Progressive Web App (PWA)] --> APIGW : Solicitudes REST
[Aplicación Android (Kotlin)] --> APIGW : Solicitudes REST
[Aplicación iOS (SwiftUI)] --> APIGW : Solicitudes REST


[Aplicación Android (Kotlin)] --> ARCore : Interacción RA
[Aplicación iOS (SwiftUI)] --> ARKit : Interacción RA

@enduml
